project_id: "860498"

base_path: "."
base_url: "https://api.crowdin.com"

preserve_hierarchy: 1

files:
  - source: /app/src/main/res/values/strings.xml
    translation: /app/src/main/res/values-%two_letters_code%/strings.xml
    languages_mapping:
      two_letters_code:
        zh-CN: zh-Hans
        zh-TW: zh-Hant
    ignore:
      - /app/src/main/res/values-v24/
      - /app/src/main/res/values-night/
